remote_theme: ankitsultana/researcher@gem

title: Caryn Tran
url: "https://caryntran.com"
baseurl: "/"

markdown: kramdown
ins_logo: "./logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "CV_2022.pdf"
 - name: "Contact"
   link: "contact"
