remote_theme: ankitsultana/researcher@gem

title: Caryn Tran
url: "https://caryntran.com"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

nav:
 - name: "About"
   link: "/"
#  - name: "Resume"
#    link: "resume.pdf"
#  - name: "Contact"
#    link: "contact"